### PR TITLE
Add documentation explaining the permission system

### PR DESCRIPTION
**Pull request by dalonsoa**
In particular, what users can or cannot do depending on their status.

It also makes several changes to the code to actually enforce what is being explained.

### CODE REVIEW

**Review by Sahil590 — APPROVED** [review]
lgtm

**Review by tsmbland — APPROVED** [review]
Looks good. Just a few typos. It would also be worth talking about Station objects, which have three visibility levels (public, private, internal), which controls the visibility of measurements associated with the station

**Comment by tsmbland** [comment]
I think the permissions levels for stations are:
- Public: all users can view measurements
- Internal: measurements cannot be viewed by anonymous users
- Private: only the station owner can view measurements

**Comment by dalonsoa** [comment]
Goo point! Have a look at the changes in https://github.com/ImperialCollegeLondon/paricia/pull/297/commits/0e86559682a3303fe52fcf130c5c00df8738f047 explaining the internal bit.

**Review by tsmbland — APPROVED** [review]
LGTM!

**Pull request merged**
