### PR TITLE
Updated data report frontend

### LINKED ISSUE #178: Integrate reporting backend with front end (plots and tables)
Use the new reporting code and model in the new report dash app.

### PR DESCRIPTION
**Pull request by CWestICL**
Code changes to `measurement.reporting.py` and `validated.dash_apps.finished_apps.data_report.py` to reflect the changes made to the reporting back end in #171.

Closes #178

### CODE REVIEW

**Comment by CWestICL** [comment]
Opened as a draft for @dalonsoa to look at, as I currently can't get `get_report_data_from_db` to return a dataframe with actual entries in it.

**Comment by dalonsoa** [comment]
@CWestICL , I've made a couple of changes that pull - and plot - the right data in 692280c, assuming the selected combination of temporality, station, variable and dates exist in the database. However, if you use the initial data, you will see nothing because that data is added to the database in bulk and that has some limitations that I'm fixing in #199 . If you use the synthetic data generator (stopping early) and check the admin to choose an appropriate combination of values, then it should work. 

Or wait until #199 is done :)

**Comment by dalonsoa** [comment]
@CWestICL , #200 is merged in `develop`, so this is ready for you to merge that branch in here and check if things work.

**Comment by dalonsoa** [comment]
I don’t know when exactly you branched off developed, but you might need to completely recreate the container and the database. Have you tried:

docker compose down
docker compose up -d —build

?

**Comment by CWestICL** [comment]
Ah right, I had deleted the containers directly from Docker before rebuilding it but I guess that wasn't enough. I've got it working now!

**Comment by CWestICL** [comment]
Data Report page should be working for the `Raw measurement` and `Validated measurement` temporality options. `Hourly`, `Daily` and `Monthly` reports do not plot for reasons outlined in #208

**Comment by tsmbland** [comment]
Looks good, however I can't get it to show any actual data. It just says 'Data not found'. I could be doing something wrong, but maybe it's worth merging the latest changes from develop to see if that fixes things

**Comment by CWestICL** [comment]
I've updated the branch if you wanted to check that the data is plotting now. Have you loaded the initial data after building the container? The `Raw measurement` report should be plotting that, and the `Validated measurement` report should have data once it's been validated.

**Review by dalonsoa — APPROVED** [review]
The dataframe to plot was unsorted, and so the plot looked weird. I've sorted that.

**Comment by CWestICL** [comment]
@dalonsoa that change seems to have messed something up in the CI tests

**Comment by dalonsoa** [comment]
Fixed! Check now

**Review by tsmbland — APPROVED** [review]

**Pull request merged**
