### PR TITLE
Upgrade pre-commit tools versions

### PR DESCRIPTION
**Pull request by dalonsoa**
The versions of the tools used by pre-commit (in particular, sort) were outdated. I just used the last version of them.

### CODE REVIEW

**Comment by dalonsoa** [comment]
@pxjacomex , the checks are failing because the new version of `black` run by `pre-commit` format the code in a slightly different way. I had run black in all the code to fix this but I've realised that will create a lot of conflicts when trying to integrate your code, so I've undone that commit.

What we are going to do is

- you have a look at the changes I've made - see above "Files Changed"
- you approve the PR
- I merge the PR it into the develop branch
- you bring the changes in the develop branch into your working branch
- you run `pre-commit` in all files in your branch with `pre-commit run --all-files`

Does it make sense?

**Review by pxjacomex — APPROVED** [review]
I tested those changes and it seems to work as expected.

**Comment by pxjacomex** [comment]
> @pxjacomex , the checks are failing because the new version of `black` run by `pre-commit` format the code in a slightly different way. I had run black in all the code to fix this but I've realised that will create a lot of conflicts when trying to integrate your code, so I've undone that commit.
> 
> What we are going to do is
> 
>     * you have a look at the changes I've made - see above "Files Changed"
> 
>     * you approve the PR
> 
>     * I merge the PR it into the develop branch
> 
>     * you bring the changes in the develop branch into your working branch
> 
>     * you run `pre-commit` in all files in your branch with `pre-commit run --all-files`
> 
> 
> Does it make sense?

Sure, I'm going to do your recommendations. Thanks.

**Comment by dalonsoa** [comment]
@pxjacomex , the PR has been merged, so now the changes are in the develop branch. Merge those into your own branch before further development.

**Pull request merged**
